console.log("Hi there!");
console.log("I am excited to talk to you.");
let bot;
let botLocation;
bot = "teacherBot";
botLocation = "the universe";
console.log("Allow me to introduce myself.");
let botIntroduction = "My name is " + bot + ".";
console.log(botIntroduction);
let botLocationSentence = "I live in " + botLocation + ".";
console.log(botLocationSentence);
bot = "professorBot";
let nicknameIntroduction = "My nickname is " + bot + ".";
console.log(nicknameIntroduction);
bot = "awesomeTeacherBot";
let newNicknameGreeting =
  "I love my nickname but I wish people would call me " + bot + ".";
console.log(newNicknameGreeting);
let favoriteSubject = "Computer Science";
let favoriteSubjectSentence = "My favorite subject is " + favoriteSubject + ".";
console.log(favoriteSubjectSentence);
console.log("Well, it was nice to talk to you. Have a nice day!");
